CRAZYGF_TWILIO_SECRET = ENV['CRAZYGF_TWILIO_SECRET'] || raise("Please set twilio secret.")
CRAZYGF_TWILIO_ACCOUNT_SID = ENV['CRAZYGF_TWILIO_ACCOUNT_SID'] || raise("Please set twilio account SID.")
CRAZYGF_TWILIO_MOBILE_NUMBER = ENV['CRAZYGF_TWILIO_MOBILE_NUMBER'] || raise("Please set twilio mobile number.")
CRAZYGF_TWILIO_SMS_URL = ENV['CRAZYGF_TWILIO_SMS_URL'] || raise("Please set twilio sms url.")
CRAZYGF_TWILIO_VOICE_URL = ENV['CRAZYGF_TWILIO_VOICE_URL'] || raise("Please set twilio voice url.")